service: default
runtime: python37
handlers:
   - url: /
     script: home.app

   - url: /(.*\.(gif|png|jpg|css))$
     static_files: static/\1
     upload: static/.*\.(gif|png|jpg|css)$

   - url: /.*
     script: auto
